### ISSUE TITLE
Не верные значения параметров

### ISSUE THREAD

**Issue by kochetovd** [initlabopen/mysqlconfigurer#1]
Параметр innodb_buffer_pool_instances должен быть равен целому количеству ГБ в innodb_buffer_pool_size.
Из рекомендаций mysqltuner можно добавить установку параметров:
1) table_definition_cache - Оставлять по умолчанию если не требуется увеличение
2) innodb_log_file_size - 25% от innodb_buffer_pool_size

**Comment by drupaladmin** [comment]
fixed
