### ISSUE TITLE
Is there any way to skip SSL certificate in the bash script?

### ISSUE THREAD

**Issue by darkhan** [initlabopen/mysqlconfigurer#19]
`root@sud:~# wget https://raw.githubusercontent.com/initlabopen/mysqlconfigurer/master/mysqlconfigurer.sh
--2020-03-11 19:17:12--  https://raw.githubusercontent.com/initlabopen/mysqlconfigurer/master/mysqlconfigurer.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted.
ERROR: The certificate of ‘raw.githubusercontent.com’ hasn't got a known issuer.`

`root@sud:~# curl -o mysqlconfigurer.sh  https://raw.githubusercontent.com/initlabopen/mysqlconfigurer/master/mysqlconfigurer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.`

I think I might have a problem with local issuer certificates, but reinstalling ca-certificates didn't help me.

**Comment by drupaladmin** [comment]
Hi.

What Operating System and version do you use?

**Comment by darkhan** [comment]
Hi

It is Debian 9.2

**Comment by drupaladmin** [comment]
you could try https://unix.stackexchange.com/questions/334905/how-do-i-fix-wget-on-an-http-url-not-trusted-errors-in-kali

Did you try to use wget with any other urls over https?

**Comment by darkhan** [comment]
Yes, I tried to re-install ca-certificates, but it didn't help.
wget with --no-check-certificate works, but this not solve the working of bash script itself.

**Comment by drupaladmin** [comment]
Did you try to use wget with any other urls over https?

**Comment by darkhan** [comment]
If you ask me about downloading the bash script I've done it, but the script is not working. 
I've got next errors:
`root@server:~# /bin/bash mysqlconfigurer.sh
rm: cannot remove '/tmp/.mysqlconfigurer//*': No such file or directory
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LC_TERMINAL = "iTerm2",
	LC_TERMINAL_VERSION = "3.3.9",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Can't open perl script "/tmp/.mysqlconfigurer/mysqltuner.pl": No such file or directory




--------MySQLTuner completed with error--------

Check /tmp/.mysqlconfigurer/mysqltunerreport.json for details

--------Please fix the error and run again--------
root@server:~# cat /tmp/.mysqlconfigurer/mysqltunerreport.json
cat: /tmp/.mysqlconfigurer/mysqltunerreport.json: No such file or directory`

**Comment by drupaladmin** [comment]
could you try to execute:
curl -o /tmp/mysqltuner.pl -L http://mysqltuner.pl/

**Comment by darkhan** [comment]
`curl -k -o /tmp/mysqltuner.pl -L http://mysqltuner.pl/`
With "-k" it worked! What should be my next step? 
I've tried to copy mysqltuner.pl file to /tmp/.mysqlconfigurer folder and then execute the script, but it didn't work also. After executing the script /tmp/.mysqlconfigurer folder becomes empty.

`root@server:~# cp /tmp/mysqltuner.pl /tmp/.mysqlconfigurer/mysqltuner.pl

root@server:~# ls /tmp/.mysqlconfigurer/
mysqltuner.pl

root@server:~# head /tmp/.mysqlconfigurer/mysqltuner.pl
#!/usr/bin/env perl
# mysqltuner.pl - Version 1.7.19
# High Performance MySQL Tuning Script
# Copyright (C) 2006-2018 Major Hayden - major@mhtx.net
#
# For the latest updates, please visit http://mysqltuner.com/
# Git repository available at https://github.com/major/MySQLTuner-perl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by

root@server:~# /bin/bash mysqlconfigurer.sh
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LC_TERMINAL = "iTerm2",
	LC_TERMINAL_VERSION = "3.3.9",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Can't open perl script "/tmp/.mysqlconfigurer/mysqltuner.pl": No such file or directory

--------MySQLTuner completed with error--------

Check /tmp/.mysqlconfigurer/mysqltunerreport.json for details

--------Please fix the error and run again--------`

**Comment by drupaladmin** [comment]
I think this is a local issue. 

Could you download the script https://raw.githubusercontent.com/initlabopen/mysqlconfigurer/master/mysqlconfigurer.sh and 
 and add "-k" option for all curl calls in it (there are 2 calls)?

**Comment by darkhan** [comment]
I agree with you, it is a local issue, I'll try to solve it with my network administrator.
Thank you for your help!
