### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by abatitskiy1** [initlabopen/mysqlconfigurer#27]
Hello!
I tried to use your script, but as a result I got file z_aiops_mysql.cnf
**# 500 Internal Server Error Oh no! Something bad happened. Please check supported MySQL versions. Thanks.** 
To be sure I checked MySQL version.
**$ mysql -v
.......
Server version: 5.5.65-MariaDB MariaDB Server**
And then I checked the length of mysqltuner report - it's non empty.
**-rw-r--r--. 1 adm77807 domain users  30535 Apr 29 14:00 mysqltunerreport.json**

Could you help me, please?
Thanks!
Aleksey B.

**Comment by drupaladmin** [comment]
Hi.

Thank you for your feedback. 

We checked the logs.
The problem is in the MySQLTuner report: All databases "Total Size":"NULL"

Could you tell me is there any databases on your server?

**Comment by abatitskiy1** [comment]
Yes, it has two DB.
One - information_schema
Second - zabbixdb

> MariaDB [(none)]> SELECT table_schema AS "Database",  ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS "Size (MB)"  FROM information_schema.TABLES  GROUP BY table_schema;
> +--------------------+-----------+
> | Database           | Size (MB) |
> +--------------------+-----------+
> | information_schema |      0.07 |
> | zabbixdb           |  75543.72 |
> +--------------------+-----------+
> 2 rows in set (0.66 sec)
> 

The problem is that database available only for specific user and I did not find any command line options for your script to provide username and password for DB access.
Yes, I can edit a script and add credentials to **mysqltuner** command line. May I?

**Comment by drupaladmin** [comment]
Yes, you could try to do it, but for the best result we need to start under user with full access to all databases.
Also you could create ~/.my.cnf file

**Comment by abatitskiy1** [comment]
OK, thanks.
I finished with ~/.my.cnf file

**Comment by drupaladmin** [comment]
Hi.

Considering your experience with MySQLConfigurer, how likely are you to recommend MySQLConfigurer to a friend or colleague if they will have performance issue with MySQL? (0-10)
