### ISSUE TITLE
Нужно предупреждение об изменении innodb_log_file_size 

### ISSUE THREAD

**Issue by susaninpro** [initlabopen/mysqlconfigurer#36]
Так просто нельзя же менять значение innodb_log_file_size. Это может повлечь проблемы с рестартом сервера. Нужны какие-то инструкции и рекомендации как правильно скорректировать это, чтобы не попасть впросак вам как сервису

**Comment by drupaladmin** [comment]
Спасибо, за обратную связь. 
Как считаете в каком виде удобней было бы вывести это замечание?

**Comment by susaninpro** [comment]
Думаю стоит сделать в виде инструкции.

С уважением,
Алексей Мокрушин
Директор по цифровым продуктам
ООО Аналитический центр "Провинция"

ИА "Сусанин"
Facebook: https://facebook.com/susanin.news
VK: https://vk.com/susanin.news
Twitter: https://twitter.com/susaninudm
Instagram: https://www.instagram.com/susanin.news
Одноклассники: https://ok.ru/susaninpro
Telegram: https://telegram.me/susaninbot


Тел: +7 (3412) 570756
skype: alexey.mokrushin
моб/tg/whatsapp/viber: +7 (912) 8544040


ср, 27 мая 2020 г. в 13:46, Roman Agabekov <notifications@github.com>:
