### ISSUE TITLE
Do not working with MariaDB 10.4

### ISSUE THREAD

**Issue by drupaladmin** [initlabopen/mysqlconfigurer#39]
The script do not working with mariadb 10.4

**Comment by progreccor** [comment]
any thoughts about the release time?

**Comment by drupaladmin** [comment]
Hi.

We plan to release MySQL 8 and MariaDB 10.4/10.5 support within a week

**Comment by progreccor** [comment]
@drupaladmin great! looking forward to it!

**Comment by drupaladmin** [comment]
Today we added MySQL 8 support.
You could try to use MySQLConfigurer on newest versions of Mysql and MariaDB
